### PR TITLE
11 Task Entity Implementation

### PR DESCRIPTION
**Pull request by Fard-Faru**
Implemented Task Entity with Factory with Documentation and Unit tests

### CODE REVIEW

**Review by DanielLivshits — APPROVED** [review]
Looks good!

**Review by scissorkhizer — APPROVED** [review]
Looks good! There's a minor typo in the method under the TaskFactory class: it's called "creatTask" instead of "createTask" but this obviously does not make a difference. Thanks for setting up the Task entity.

**Comment by Fard-Faru** [comment]
Hi @scissorkhizer Thanks for pointing out the mistake, I'll push a fix since it's important we have our base done perfectly so there's no problems for parallel workflow.

**Review by scissorkhizer — APPROVED** [review]
Looks completely good now!

**Comment by POPPININ** [comment]
Look good to me too. However, it isn't evident (on a first glance) as to why the constructor for Task is protected. Might make sense to add a comment or two on why that decision was made.

**Review by POPPININ — APPROVED** [review]

**Review by DanielLivshits — APPROVED** [review]

**Pull request merged**
