### PR TITLE
66 Refactor Most Warnings

### PR DESCRIPTION
**Pull request by Fard-Faru**
## Modification: Refactor Most Warnings

Description:  
Refactor Most Warnings

### Important Notes:
DOCUMENT WHATEVER WE DIDNT RESOLVE TO SHOW WE KNOW WHAT WE'RE DOING

### CODE REVIEW

**Review by scissorkhizer — APPROVED** [review]
The warnings exploded with mentions of "referring static method from instance", so stuff needed to be refactored within the tests to change each instance calling getDays to WeekDataAccess.getDays(), gross refactoring but thank you for changing that.

**Review by DanielLivshits — APPROVED** [review]
Addresses the necessary IntelliJ warnings. Thank you for the refactoring changes.

**Review by eatingcorn — APPROVED** [review]
Thanks for addressing most of Intellij's warnings, looks good.

**Review by missionStrawberry — APPROVED** [review]
Looks good! Thanks for handling the warnings again Fardin!

**Pull request merged**
